osx_image: xcode8.3
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1
before_install:
  - open -a "simulator" --args -CurrentDeviceUDID F60B87EC-8969-41A7-90ED-D0826ECC32DB
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --project-directory=Example --repo-update

script:
  - "! git grep ' $'" # Fail on trailing whitespace
  - ./test.sh
  - pod lib lint FirebaseCommunity.podspec --verbose | tail -40
